name : push and deploy

# Event
on:
  push:
    branches: [ "main" ]	

# Job
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: connect and git pull
      - uses: appleboy/ssh-action@master
        with:
          host : ${{secrets.host}}
          username : ${{secrets.name}}
          password : ${{secrets.password}}
          port : ${{secrets.port}}
          script: |
            cd workspace/action
            git checkout main
            git pull
      
